title: Peter Moorey
description: > # this means to ignore newlines until "baseurl:"
  Peter Moorey's personal blog about network architecture, automation and cyber security
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://petermoorey.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Peter Moorey
author-img: petermoorey.jpg
about-author: Hello! I'm a Network Architect focusing on automation and security. When I'm not travelling I'm writing Python in VS Code!
social-twitter: petermoorey
social-facebook: peter.moorey
social-github: petermoorey
social-linkedin: pmoorey
social-email: petermoorey@gmail.com

# Disqus
discus-identifier:

# Tracker
analytics: UA-175426526-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
